export const COMMON_ERROR = 'COMMON_ERROR';
export const BAD_REQUEST = 'BAD_REQUEST';
export const SERVER_ERROR = 'SERVER_ERROR';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const HTTP_CONFLICT = 'HTTP_CONFLICT';
